"""empty message

Revision ID: dc9239cffef1
Revises: 95ff97ca03a1
Create Date: 2023-01-31 00:55:42.227316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9239cffef1'
down_revision = '95ff97ca03a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dbid', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('showtime', sa.Integer(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('filesize', sa.Integer(), nullable=True),
    sa.Column('cdate', sa.DateTime(), nullable=True),
    sa.Column('display_quality', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('face', sa.String(), nullable=True),
    sa.Column('look', sa.String(), nullable=True),
    sa.Column('age', sa.String(), nullable=True),
    sa.Column('pussy', sa.String(), nullable=True),
    sa.Column('etc', sa.String(), nullable=True),
    sa.Column('school_uniform', sa.Boolean(), nullable=True),
    sa.Column('hip', sa.Boolean(), nullable=True),
    sa.Column('group', sa.Boolean(), nullable=True),
    sa.Column('pregnant', sa.Boolean(), nullable=True),
    sa.Column('conversation', sa.Boolean(), nullable=True),
    sa.Column('lesbian', sa.Boolean(), nullable=True),
    sa.Column('ani', sa.Boolean(), nullable=True),
    sa.Column('oral', sa.Boolean(), nullable=True),
    sa.Column('masturbation', sa.Boolean(), nullable=True),
    sa.Column('massage', sa.Boolean(), nullable=True),
    sa.Column('uniform', sa.Boolean(), nullable=True),
    sa.Column('family', sa.Boolean(), nullable=True),
    sa.Column('ad_start', sa.Integer(), nullable=True),
    sa.Column('ad_finish', sa.Integer(), nullable=True),
    sa.Column('star', sa.Integer(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('date_modified', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_video'))
    )
    op.create_index(op.f('ix_video_dbid'), 'video', ['dbid'], unique=True)
    op.create_index(op.f('ix_video_id'), 'video', ['id'], unique=False)
    op.drop_column('manga', 'page')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manga', sa.Column('page', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_video_id'), table_name='video')
    op.drop_index(op.f('ix_video_dbid'), table_name='video')
    op.drop_table('video')
    # ### end Alembic commands ###
